name: Test

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '__tests__/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '__tests__/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test

  coverage:
    needs: test
    name: Coverage
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/coverage.yml
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
